### ISSUE TITLE
 The engine "node" is incompatible with this module. Expected version ">=4 <=9".

### ISSUE THREAD

**Issue by Narven** [anodynos/upath#20]
On circleci I'm getting this error for this lib:

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

any ideas?

**Comment by misund** [comment]
Fixed in #15; try deleting your package-lock.json or yarn.lock and install dependencies again.

**Comment by Narven** [comment]
@misund  thanks it worked

**Comment by narrowtux** [comment]
What kind of solution is deleting your lock files, I don't really want to ensure everything works again after installing random versions of all my dependencies

**Comment by JGallardo** [comment]
For those googling the error and ending up here
* Delete your yarn.lock
* in your terminal run `yarn`
That will generate a new file with updated dependencies.
