### ISSUE TITLE
Please update Node dependency to include v10

### ISSUE THREAD

**Issue by digitalclover** [anodynos/upath#21]
Since Node recently released version 10, I'm receiving the following error when trying to install upath.

`The engine "node" is incompatible with this module. Expected version ">=4 <=9".                                                                                   `

Can you update the compatibility to include `<=10`?

**Comment by JeffJacobson** [comment]
Looking through the other issues when I encountered this, it looks like this has already been fixed (#15). You need to delete the "lock" file and then run install again and it will work.

**Comment by digitalclover** [comment]
My bad. Updating the lock file fixed this issue. Thanks!
