### ISSUE TITLE
Incompatible with node v10

### ISSUE THREAD

**Issue by jsnanigans** [anodynos/upath#24]
With node v10.4.1 I am getting this error:
`error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`
if I switch to node v8 it works

**Comment by NickHeiner** [comment]
Can you just upgrade to `upath@1.1.0`?

**Comment by nikolakanacki** [comment]
This broke like half the things on the npm, I'm kind of used to writing `yarn add ... --ignore-engines` now.

**Comment by jsnanigans** [comment]
@NickHeiner id rather not because its a dependency of one of my dependencies

**Comment by NickHeiner** [comment]
@nikolakanacki ah, I didn't know about that! That's a useful workaround. 😄 

> id rather not because its a dependency of one of my dependencies

`upath` was a transitive dependency for me too, but I was able to update my immediate dependencies, which in turn pulled in a newer `upath`.

**Comment by anodynos** [comment]
The latest (`upath@1.1.0`) works with node 10 - ask the devs of the libraries that use the old upath version to update - there's nothing I can do :-(
