### ISSUE TITLE
why not use path.posix ?

### ISSUE THREAD

**Issue by pq1949** [anodynos/upath#26]
http://nodejs.cn/api/en/path.html#path_path_posix

**Comment by anodynos** [comment]
I am not familiar with it, nor I can really understand what it does from the limited docs: 
________________
# path.posix#

Added in: v0.11.15
<Object>
The path.posix property provides access to POSIX specific implementations of the path methods.
________________

What are you suggesting?

**Comment by pq1949** [comment]
![image](https://user-images.githubusercontent.com/9245399/44217298-b6031380-a1a9-11e8-9790-e50c92c48a9f.png)

if we just want this feature , path.posix is enougth 
`path.win32` is windows style path  `\`
`path.posix`  is unix style path. `/`

**Comment by rswalkden** [comment]
@pq1949 `path.posix` won't replace the backslashes. If you run:
`path.posix.normalize('c:\\test\\test.jpg')` it'll just spit `"c:\\test\\test.jpg"` right back at you.

**Comment by pq1949** [comment]
@rswalkden  @anodynos 
I have known the differentia ,thank you for your answers
![image](https://user-images.githubusercontent.com/9245399/45466028-7698fa00-b74a-11e8-8825-fcc7b78f2b9b.png)

**Comment by anodynos** [comment]
I'm glad upath does it better :-)
And it's such a few lines of code...

**Comment by pq1949** [comment]
@anodynos yeah，nice work！ Thank you very much!
