### ISSUE TITLE
Missing tag / release for v1.0.4

### ISSUE THREAD

**Issue by intelliot** [anodynos/upath#28]
Looking for upath@1.0.4

**Comment by intelliot** [comment]
I don't see v1.1.0 here either: https://github.com/anodynos/upath/releases

We want to access the code for v1.0.4 so that we can compare the differences between it and later versions (what was changed?)

**Comment by anodynos** [comment]
Sorry, I haven't updated the *releases* - you can find the different versions published on npm.
There are some tags in place, this is 1.0.5 https://github.com/anodynos/upath/releases/tag/v1.0.5
There aren't that many commits in this repo, so you can easily find what's changed.
