### ISSUE TITLE
`removeExt` for Extensions > 7 Chars

### ISSUE THREAD

**Issue by yucho** [anodynos/upath#32]
First of all, thanks for this awesome module! Been using it for quite long and am thoroughly happy with it. My issue is that currently `removeExt` has no way to remove extensions longer than default `maxSize`, which is 7. The workaround I use is something like:
```JavaScript
// I want to do:
newName = upath.removeExt(filename, '.longer_than_7');

// Workaround:
const ext = upath.extname(filename);
if (upath.extname(filename) === '.longer_than_7') {
  newName = upath.trimExt(filename, [], ext.length);
}
```
However, since we are passing the exact extname to remove, I see no point in restricting its length. There are sizable number of extensions that are longer than 7 characters (`.application, .gameproj, .layout, .mustache, .partial` to name a few).

If you don't mind, I made a quick one-liner fix and would like to submit a pull request for your review. But if this is the behavior you want, I will stick with my old workaround.

**Comment by anodynos** [comment]
Doesnt [this work for your case](https://github.com/anodynos/upath#examples--specs-4)? `upath.removeExt(filename, ['min', '.dev'], 8)`          --returns-->

**Comment by yucho** [comment]
Cool! Going to doc it and submit soon.

**Comment by yucho** [comment]
Also, there's a typo in the [2nd example](https://github.com/anodynos/upath#upathtrimextfilename-ignoreexts-maxsize7) of `trimExt` doc where the function is misspelled `removeExt`. I can quickly fix it and make a separate PR if you want.

**Comment by anodynos** [comment]
Thanks & sorry for delay, I somehow missed it...! I will review and merge soon-ish (this wkd)

**Comment by anodynos** [comment]
> Also, there's a typo in the [2nd example](https://github.com/anodynos/upath#upathtrimextfilename-ignoreexts-maxsize7) of `trimExt` doc where the function is misspelled `removeExt`. I can quickly fix it and make a separate PR if you want.

Go ahead and fix it in this PR, its fine :-)

**Comment by yucho** [comment]
@anodynos Sorry for the late response! I just updated the PR accordingly.
