### ISSUE TITLE
upath.resolve() not replacing slashes

### ISSUE THREAD

**Issue by robross0606** [anodynos/upath#35]
```javascript
const path = require('upath')
const REPORT_RESOURCE_PATH = path.resolve(__dirname, `../../../reports`)
```
Ends up returning:
`"C:\Code\ncp\study-design-service\reports"`
Not only were the slashes not replaced, they were actually converted the wrong direction?  O_o

**Comment by robross0606** [comment]
Doing this _does_ finally convert them:
```javascript
path.toUnix(path.resolve(__dirname, `../../../reports`))
```
However, this shouldn't be necessary as per the API docs.

**Comment by anodynos** [comment]
Thanks for the issue - I will have a look. 

Can you please provide full examples, with the actual input values (I can't possibly know what `__dirname` is in you examples) 

Thanks

**Comment by robross0606** [comment]
Yes.  Windows 10 with node 12.x

**Comment by anodynos** [comment]
Ok, this is confusing. I'm on Windows 10 / node 12.18.0 and I just run the example and it worked as expected: 

``` 
const upath = require('upath')
console.log(upath.resolve("C:\\Code\\ncp\\study-design-service\\src\\graphql\\resolvers", "../../../reports"))
// => C:/Code/ncp/study-design-service/reports
console.log(__dirname)
// => E:\projects\permissions\DRAFT
console.log(upath.resolve(__dirname, "../../reports"))
// => E:/projects/reports
```

**Comment by robross0606** [comment]
One thing I see different here is you're not using `__dirname`.  I don't believe slashes are escaped when using `__dirname`?  It is not this:
"C:\\Code\\ncp\\study-design-service\\src\\graphql\\resolvers"
It is this at least according to the debugger:
"C:\Code\ncp\study-design-service\src\graphql\resolvers"
However, I just tested this again and it is now working.  I logged this ticket several months ago, so maybe something in node was fixed in the interim?

**Comment by anodynos** [comment]
I do use `__dirname` on the 2nd one, cause I thought it might make a difference.

I haven't changed this library lately, no... weird!

Anyway, good opportunity to add a test for resolve & also check node 13 & 14:-) 

Thanks for the issue!

**Comment by robross0606** [comment]
Yeah, curious.  NodeJS has had a few updates since April so maybe something was resolved there.  Wish I had included the node version in the original ticket. Sorry.

**Comment by anodynos** [comment]
BTW, how can you develop on Windows - I can't find a proper console and I miss zsh so much. 
Nothing beats Linux (I use Kubuntu) for development IMHO :-)

**Comment by robross0606** [comment]
With great difficulty.  😄  WSL helps a bit for many things.  Haven't given WSL2 a try yet since I'm wary of the side-effects from being backed by Hyper-V.

**Comment by anodynos** [comment]
I see, I guess you have to use Windows.... good luck!
