### ISSUE TITLE
Proxied methods don't work in jest

### ISSUE THREAD

**Issue by abuzhynsky** [anodynos/upath#40]
Hello.

Thanks for the awesome project.

Unfortunately, the `path`'s proxied methods don't work in `jest`. `upath` uses the [`instanceof Function` check](https://github.com/anodynos/upath/blob/master/source/code/upath.coffee#L3) and [`instanceof` based checks are broken in `jest`](https://github.com/facebook/jest/issues/2549).

Seems that `jest` won't get a fix of this issue soon - context isolation (tests can't have side-effects on other tests by manipulating the global context) is an important feature and the fix isn't trivial. :disappointed: 

Maybe it's possible to use another `isFunction` check?

There are [some options](https://stackoverflow.com/questions/5999998/check-if-a-variable-is-of-function-type). They are cryptic but can be helpful.

Thanks in advance.

**Comment by anodynos** [comment]
Wow, what an issue @abuzhynsky ;-)

I don't mind at all using another solid way to check for function - I would happily accept a PR for it if you want to have a go ;-)

**Comment by abuzhynsky** [comment]
Hello, @anodynos.

Sorry for the late answer.

Unfortunately I'm not an expert in these checks. :disappointed: 

Anyway, I think that the `lodash` guys have much more expertise than me.

So I propose to use their implementation (I've tested it, it works with `jest`). Their [current master branch implementation is based on the `typeof` check](https://github.com/lodash/lodash/blob/master/isFunction.js#L30). I propose to use it (I'll send a PR).

But their last published tag in `npm` [has more complicated implementation](https://github.com/lodash/lodash/blob/4.17.20/lodash.js#L11673) based on the `Object#toString` to avoid issues with `typeof` in Safari 9. However, I think that it's not an issue for the Node JS targeted package and we can avoid the unnecessary complexity and use the `typeof` check.

**Comment by anodynos** [comment]
This is great - the `typeof` check is well known, we'll go with that! Thanks so much!
