### ISSUE TITLE
Would you consider using the lodash single-method packages?

### ISSUE THREAD

**Issue by davej** [anodynos/upath#9]
`upath` is quite a hefty module at ~2MB, mainly because of `lodash`. Would you consider using the single-method packages instead? i.e.. https://www.npmjs.com/package/lodash.map

**Comment by anodynos** [comment]
Well, its a server side / nodejs package so it doesn't really matter, does it?

**Comment by davej** [comment]
I'm using it in an Electron app, so it all adds to the binary size which makes the app slower to download. But I think it's generally good to have smaller packages if possible. Loading all of `lodash` into memory costs memory, memory isn't free.

Your call of course :-)

**Comment by billyjanitsch** [comment]
Hi @anodynos! The method used in e359938 is not the best approach (the per-method Lodash packages are deprecated), but there is a better way of only importing the needed parts of Lodash into memory. I wrote up an explanation [here](https://github.com/tldr-pages/tldr-node-client/issues/185). Happy to submit a PR if you'd like.
